name = "ai-vibez"
main = "dist/_worker.js"
compatibility_date = "2024-10-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ai-vibez-d1"
database_id = "88c494f1-1236-4ce4-8b60-570776559000"

[[durable_objects.bindings]]
name = "CodeGenObject"
class_name = "CodeGeneratorAgent"

[[durable_objects.bindings]]
name = "Sandbox"
class_name = "UserAppSandboxService"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = [
  "CodeGeneratorAgent",
  "UserAppSandboxService"
]
