name = "ai-vibez"
main = "dist/_worker.js"
compatibility_date = "2024-10-02"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "2101"

[[unsafe.bindings]]
name = "AUTH_RATE_LIMITER" 
type = "ratelimit"
namespace_id = "2102"

[ai]
binding = "AI"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "ai-vibez-db"
database_id = "YOUR_D1_DATABASE_ID_HERE"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "CodeGenObject"
class_name = "CodeGeneratorAgent"

[[durable_objects.bindings]]
name = "Sandbox"
class_name = "UserAppSandboxService"

[[durable_objects.bindings]]
name = "DORateLimitStore"
class_name = "DORateLimitStore"

[[r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "ai-vibez-r2"

[[kv_namespaces]]
binding = "VibecoderStore"
id = "YOUR_KV_NAMESPACE_ID_HERE"

# Static assets binding for serving frontend files
[assets]
binding = "ASSETS"
directory = "dist"

[vars]
# Application Configuration
TEMPLATES_REPOSITORY = "https://github.com/Carter-75/ai-vibez"
CLOUDFLARE_AI_GATEWAY = "ai-vibez-gateway"
MAX_SANDBOX_INSTANCES = "10"
SANDBOX_INSTANCE_TYPE = "standard"

# Authentication Configuration - LOGIN IS REQUIRED!
ENABLE_EMAIL_WHITELIST = "false"  # Set to "true" to restrict access to specific emails
DISABLE_EMAIL_AUTH = "false"      # Keep false - provides email/password backup login
ALLOWED_EMAIL = "cartermoyer75@gmail.com"  # Admin email address
REQUIRE_AUTHENTICATION = "true"   # Users MUST log in to use the app

# Security Settings
ENVIRONMENT = "production"
SESSION_TIMEOUT_HOURS = "24"      # How long users stay logged in